export const BASE_URL = 'https://qrpro-1.onrender.com';

export const COLORS = {
  bg: '#080807',
  surface: '#0f0e0c',
  card: '#141210',
  cardHover: '#1a1816',
  ember: '#c8873a',
  emberGlow: '#e0a050',
  emberDim: '#8a5a20',
  cream: '#f2e8d9',
  creamMuted: '#9a8a7a',
  divider: 'rgba(200, 135, 58, 0.18)',
  success: '#22c55e',
  danger: '#ef4444',
  pending: '#f59e0b',
  prep: '#3b82f6',
};

export const ROLES = [
  {
    id: 'customer',
    title: 'Customer Menu',
    subtitle: 'Browse menu & place orders',
    icon: '📱',
    gradient: ['#c8873a', '#e0a050'],
    requiresLogin: false,
    pathBuilder: (username) => `/menu/${username}`,
  },
  {
    id: 'kitchen',
    title: 'Kitchen Display',
    subtitle: 'Manage incoming orders live',
    icon: '🍳',
    gradient: ['#f59e0b', '#fbbf24'],
    requiresLogin: false,
    pathBuilder: (username) => `/kitchen/${username}`,
  },
  {
    id: 'captain',
    title: 'Captain / Waiter',
    subtitle: 'Take orders table-side',
    icon: '👨‍🍳',
    gradient: ['#3b82f6', '#60a5fa'],
    requiresLogin: false,
    pathBuilder: (username) => `/captain/${username}`,
  },
  {
    id: 'dashboard',
    title: 'Owner Dashboard',
    subtitle: 'Stats, settings & analytics',
    icon: '📊',
    gradient: ['#8b5cf6', '#a78bfa'],
    requiresLogin: true,
    path: '/dashboard',
  },
  {
    id: 'billing',
    title: 'Billing',
    subtitle: 'Table bills & settlements',
    icon: '💰',
    gradient: ['#22c55e', '#4ade80'],
    requiresLogin: true,
    path: '/billing',
  },
  {
    id: 'inventory',
    title: 'Inventory',
    subtitle: 'Manage menu items & stock',
    icon: '📦',
    gradient: ['#ef4444', '#f87171'],
    requiresLogin: true,
    path: '/inventory',
  },
  {
    id: 'orders',
    title: 'Order History',
    subtitle: 'Revenue reports & analytics',
    icon: '📋',
    gradient: ['#06b6d4', '#22d3ee'],
    requiresLogin: true,
    path: '/orders',
  },
];
